apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mvangala-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvangala-web
    spec:
      containers:
      - name: mvangalaweb
        image: docker.io/mvangala/mvangala-web:v2
        ports:
        - containerPort: 80
