kind: Service
apiVersion: v1
metadata:
  name: mvangala-web
spec:
  selector:
    app: mvangala-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-port 
    - protocol: TCP
      port: 443 
      targetPort: 443
      name: https-port
  type: LoadBalancer
  loadBalancerIP: 35.200.232.157 
