apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mvangala-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvangala-web
    spec:
      containers:
      - name: mvangalaweb
        image: docker.io/mvangala/mvangala-web:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: ssl-disk
      volumes:
      - name: ssl-disk
        gcePersistentDisk:
          pdName: mvangala-web-ssl-disk
          fsType: ext4
